### ISSUE TITLE
Simplify Build task and initial project setup

### ISSUE THREAD

**Issue by Daddoon** [Daddoon/BlazorMobile#17]
Actualy, there is a lot of manual thing to do the initial project setup and for make it working.
Installation and usage must be more easy, and at least, only adding the a NuGet package for Build Task on the .Net Standard shared project for mobile must be sufficient.

And also of course, still using the initialization code.

**Task to do:**

- [ ] ~~Use Blazor web project in the **.NET Standard** mobile project as a reference, in order to retrieve the Blazor project path~~ -> More problematic solution. It is better to separate pure Blazor dependencies to the Xamarin one in the final assembly. 
- [x] Being able to usage either **WASM** or **ServerSide** Blazor project implementation in reference in the mobile project. -> shipped in BlazorMobile 3.0.1
- [x] Create a BeforeBuild task, executed as **.NET CLI Tool** or **MSBuild Exec** that fire on the shared project, **after Blazor build**, that remove Blazor pure .NET reference (or assume **Local Copy == false**), and add an embedded ressource ZIP **WASM** version of the Blazor app project on the shared project. -> Will be shipped in BlazorMobile 3.0.3

Also, useful links:

- [MSBuild tasks with dependencies](https://natemcmaster.com/blog/2017/11/11/msbuild-task-with-dependencies/)
- [.NET Core Global Tools overview](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools)

**Comment by Daddoon** [comment]
This seem pretty old and some informations seem irrelevant now.

I think the creation of the zip, should be moved on the  "Shared" mobile project, with a project build dependency set on the Blazor wasm app.

**Comment by Daddoon** [comment]
Updated. Can now be closed. Tasks will be shipped in BlazorMobile 3.0.3
